# Generated by Django 5.0.2 on 2024-02-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
