# Generated by Django 5.0.2 on 2024-02-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('post', '0002_alter_posts_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
